# Documentation:
# https://docs.netlify.com/configure-builds/file-based-configuration

# Example SSR site
# https://github.com/AaronBeaudoin/vite-plugin-ssr-example-netlify

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "_deploy"
  included_files = ["**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200

[dev]
  port = 8080
  autoLaunch = true