name: Profiles Scrape Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * 3"
jobs:
  run-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm i
      - name: Run Scrape
        run: npm run scrape-profiles
      - name: Commit File Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add .
          git commit -m "Profiles Data Scrape"
          git push