name: Update Site Data
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"
jobs:
  update-site-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm i
      - name: Get Data
        run: node scripts/get-data.js
      - name: Commit File Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git status
          git add .
          git commit -m "Update site data (cron)"
          git push